Dandole estilos CSS al header
pazita-dev/bryant-course pull request #3
Opened 2022-08-12 00:19 UTC by karlaojeda

2022-08-12 00:36 UTC, plbryant requested changes
Two errors to resolve.

2022-08-12 00:36 UTC, plbryant commented on sitio_web/planes/index.html
> +            <li class="nav__items nav__items--highlight">Star hosting</li>
"nav__items" class should be "nav__item" in singular form.

2022-08-12 00:36 UTC, plbryant commented on sitio_web/planes/main.css
> +.nav__list-container .nav__items--highlight {
This should be a class modifier, not a block modifier.

2022-08-12 00:53 UTC, karlaojeda commented on sitio_web/planes/index.html
> +            <li class="nav__items nav__items--highlight">Star hosting</li>
ok,listo

2022-08-12 01:02 UTC, karlaojeda commented on sitio_web/planes/main.css
> +.nav__list-container .nav__items--highlight {
listo, gracias.

2022-08-13 00:01 UTC, plbryant approved these changes

2022-08-13 00:04 UTC, merged